<?php
namespace PHPUnitHelper\Reflector;

class ArgumentReflectorConverterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @TODO This method was generated by PHPUnitHelper
     */
    public function testToPHPMethodArgument()
    {
        $arg = null;
        // $expected =
        // $actual = ArgumentReflectorConverter::toPHPMethodArgument($arg);
        // $self->assertEquals($expected, $actual);
    }

}
