<?php
namespace PHPUnitHelper\Reflector;

class ClassReflectorConverterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @TODO This method was generated by PHPUnitHelper
     */
    public function testToPHPClass()
    {
        $reflectedClass = null;
        // $expected =
        // $actual = ClassReflectorConverter::toPHPClass($reflectedClass);
        // $self->assertEquals($expected, $actual);
    }

}
