<?php
namespace PHPUnitHelper\Reflector;

class MethodReflectorUtilTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @TODO This method was generated by PHPUnitHelper
     */
    public function testIsPublic()
    {
        $method = null;
        // $expected =
        // $actual = MethodReflectorUtil::isPublic($method);
        // $self->assertEquals($expected, $actual);
    }

    /**
     * @TODO This method was generated by PHPUnitHelper
     */
    public function testFilterPublic()
    {
        $methods = array();
        // $expected =
        // $actual = MethodReflectorUtil::filterPublic($methods);
        // $self->assertEquals($expected, $actual);
    }

}
