<?php
namespace PHPUnitHelper\Reflector;

class MethodReflectorConverterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @TODO This method was generated by PHPUnitHelper
     */
    public function testToPHPMethod()
    {
        $reflectedMethod = null;
        // $expected =
        // $actual = MethodReflectorConverter::toPHPMethod($reflectedMethod);
        // $self->assertEquals($expected, $actual);
    }

}
